### ISSUE TITLE
jenkins_job widget not working  

### ISSUE THREAD

**Issue by sshelake25** [kj187/dashing-jenkins_job#5]
I want to create dashboard for couple of features of Jenkins.
Sample dashboard in dashing js working but when i am trying to for jenkins_job. showing error on command line. am not able to figure out what is issue.

can somebody help me out to find resolution to this issue. 

2017-05-17T15:36:07.958Z - error: Error: Not Found
    at end (C:\BMCData\dashboard\jenkins_dashboard\node_modules\mincer\lib\mincer\server.js:1:36)
    at C:\BMCData\dashboard\jenkins_dashboard\node_modules\mincer\lib\mincer\server.js:1:28
    at Server.compile (C:\BMCData\dashboard\jenkins_dashboard\node_modules\mincer\lib\mincer\server.js:1:28)
    at Server.handle (C:\BMCData\dashboard\jenkins_dashboard\node_modules\mincer\lib\mincer\server.js:1:28)
    at C:\BMCData\dashboard\jenkins_dashboard\node_modules\mincer\lib\mincer\server.js:1:36
    at Layer.handle [as handle_request] (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\layer.js:1:28)
    at trim_prefix (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28
    at Function.process_params (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at next (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28)
    at Dashing.allowCrossDomain (C:\BMCData\dashboard\jenkins_dashboard\node_modules\new-dashing-js\lib\dashing.js:1:28)
    at Layer.handle [as handle_request] (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\layer.js:1:28)
    at trim_prefix (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28
    at Function.process_params (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at next (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28)
    at methodOverride (C:\BMCData\dashboard\jenkins_dashboard\node_modules\method-override\index.js:1:36)
    at Layer.handle [as handle_request] (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\layer.js:1:28)
    at trim_prefix (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28
    at Function.process_params (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at next (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28)
    at urlencodedParser (C:\BMCData\dashboard\jenkins_dashboard\node_modules\body-parser\lib\types\urlencoded.js:1:28)
    at Layer.handle [as handle_request] (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\layer.js:1:28)
    at trim_prefix (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28
    at Function.process_params (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at next (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28)
    at jsonParser (C:\BMCData\dashboard\jenkins_dashboard\node_modules\body-parser\lib\types\json.js:1:28)
    at Layer.handle [as handle_request] (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\layer.js:1:28)
    at trim_prefix (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28
    at Function.process_params (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at next (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28)
    at compression (C:\BMCData\dashboard\jenkins_dashboard\node_modules\compression\index.js:1:28)
    at Layer.handle [as handle_request] (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\layer.js:1:28)
    at trim_prefix (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28
    at Function.process_params (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at next (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28)
    at Layer.handle [as handle_request] (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\layer.js:1:36)
    at trim_prefix (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28
    at Function.process_params (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at next (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28)
    at logger (C:\BMCData\dashboard\jenkins_dashboard\node_modules\morgan\index.js:1:28)
    at Layer.handle [as handle_request] (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\layer.js:1:28)
    at trim_prefix (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28
    at Function.process_params (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at next (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28)
    at expressInit (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\middleware\init.js:1:28)
    at Layer.handle [as handle_request] (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\layer.js:1:28)
    at trim_prefix (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28
    at Function.process_params (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at next (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28)
    at query (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\middleware\query.js:1:28)
    at Layer.handle [as handle_request] (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\layer.js:1:28)
    at trim_prefix (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28
    at Function.process_params (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:36)
    at next (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:1:28)
    at Function.handle (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\router\index.js:174:3)
    at EventEmitter.handle (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\application.js:1:28)
    at Server.app (C:\BMCData\dashboard\jenkins_dashboard\node_modules\express\lib\express.js:1:28)
    at emitTwo (events.js:1:36)
    at Server.emit (events.js:1:28)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:1:36)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:1:36)

express deprecated res.send(status, body): Use res.status(status).send(body) instead node_modules\new-dashing-js\lib\dashing.js:201:9
GET /assets/favicon.ico 500 613.566 ms - 14

**Comment by StephenSorriaux** [comment]
Hello,

Have you got any error in the console of your navigator ?
