### ISSUE TITLE
Install fails :: no such file or directory, open 'jobs/jenkins_job.job.js'

### ISSUE THREAD

**Issue by orbmis** [kj187/dashing-jenkins_job#7]
My install is failing for some reason - below is the error message I'm getting:

Is there a way to manually install the package? If I start a new Dashing project, which files do I copy to which folders?

```
$ ./node_modules/dashing-js/bin/dashing-js install https://github.com/kj187/dashing-jenkins_job/archive/master.zip
Installing zip "https://github.com/kj187/dashing-jenkins_job/archive/master.zip"
      create  widgets/dashing-jenkins_job-master/README.md
      create  widgets/dashing-jenkins_job-master/config.jenkins_job.sample.js
      create  widgets/dashing-jenkins_job-master/jenkins_job.coffee
      create  widgets/dashing-jenkins_job-master/jenkins_job.html
      create  jobs/jenkins_job.job.js
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'jobs/jenkins_job.job.js'
Emitted 'error' event at:
    at WriteStream.onerror (/home/-------/dashboards/node_modules/unzip/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at WriteStream.emit (events.js:182:13)
    at fs.open (fs.js:2219:12)
    at FSReqWrap.oncomplete (fs.js:136:20)
```

**Comment by AndresCidoncha** [comment]
You have to create a new project first (`dashing-js new nameoftheproject`) and in the project's folder execute the install command.
