### ISSUE TITLE
Getting this error while installing on MAC

### ISSUE THREAD

**Issue by javatechy** [kj187/dashing-jenkins_job#8]
```
deepak:~/Downloads$ npm install -g dashing-js
npm WARN deprecated coffee-script@1.6.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated jade@0.35.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated ejs@0.8.8: Critical security bugs fixed in 2.5.5
npm WARN deprecated connect@2.12.0: connect 2.x series is deprecated
npm WARN deprecated constantinople@1.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@0.9.15: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/usr/local/bin/dashing-js -> /usr/local/lib/node_modules/dashing-js/bin/dashing-js

> node-sass@0.7.0 install /usr/local/lib/node_modules/dashing-js/node_modules/node-sass
> node build.js

(node:15625) [DEP0006] DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.

  CXX(target) Release/obj.target/binding/binding.o
In file included from ../binding.cpp:7:
../sass_context_wrapper.h:10:3: error: unknown type name 'uv_work_t'
  uv_work_t request;
  ^
../sass_context_wrapper.h:20:3: error: unknown type name 'uv_work_t'
  uv_work_t request;
  ^
../binding.cpp:13:20: error: unknown type name 'uv_work_t'
void WorkOnContext(uv_work_t* req) {
                   ^
../binding.cpp:19:22: error: unknown type name 'uv_work_t'
void MakeOldCallback(uv_work_t* req) {
                     ^
../binding.cpp:20:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/deepak/.node-gyp/10.8.0/include/node/v8.h:883:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../binding.cpp:21:14: error: no matching constructor for initialization of 'v8::TryCatch'
    TryCatch try_catch;
             ^
/Users/deepak/.node-gyp/10.8.0/include/node/v8.h:8438:12: note: candidate constructor not viable: requires single argument 'isolate', but no arguments were
      provided
  explicit TryCatch(Isolate* isolate);
           ^
/Users/deepak/.node-gyp/10.8.0/include/node/v8.h:8558:3: note: candidate constructor not viable: requires 1 argument, but 0 were provided
  TryCatch(const TryCatch&) = delete;
  ^
../binding.cpp:29:31: error: no matching function for call to 'Null'
            Local<Value>::New(Null()),
                              ^~~~
/Users/deepak/.node-gyp/10.8.0/include/node/v8.h:322:27: note: candidate function not viable: requires single argument 'isolate', but no arguments were
      provided
  friend Local<Primitive> Null(Isolate* isolate);
                          ^
../binding.cpp:30:39: error: no member named 'New' in 'v8::String'
            Local<Value>::New(String::New(ctx->output_string))
                              ~~~~~~~~^
../binding.cpp:30:39: warning: 'New' is deprecated [-Wdeprecated-declarations]
/Users/deepak/.node-gyp/10.8.0/include/node/v8.h:5062:10: note: 'New' has been explicitly marked deprecated here
  static V8_DEPRECATED("Use maybe version",
         ^
/Users/deepak/.node-gyp/10.8.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../binding.cpp:30:39: warning: 'New' is deprecated [-Wdeprecated-declarations]
            Local<Value>::New(String::New(ctx->output_string))
                                      ^
/Users/deepak/.node-gyp/10.8.0/include/node/v8.h:4043:12: note: 'New' has been explicitly marked deprecated here
    static V8_DEPRECATED("Use maybe version",
           ^
/Users/deepak/.node-gyp/10.8.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../binding.cpp:33:24: error: member reference type 'v8::Persistent<v8::Function>' is not a pointer; did you mean to use '.'?
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
        ~~~~~~~~~~~~~~~^~
                       .
../binding.cpp:33:26: error: no member named 'Call' in 'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
        ~~~~~~~~~~~~~~~  ^
../binding.cpp:33:40: error: no member named 'GetCurrent' in 'v8::Context'
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
                              ~~~~~~~~~^
../binding.cpp:38:39: error: no member named 'New' in 'v8::String'
            Local<Value>::New(String::New(ctx->error_message))
                              ~~~~~~~~^
../binding.cpp:38:39: warning: 'New' is deprecated [-Wdeprecated-declarations]
/Users/deepak/.node-gyp/10.8.0/include/node/v8.h:5062:10: note: 'New' has been explicitly marked deprecated here
  static V8_DEPRECATED("Use maybe version",
         ^
/Users/deepak/.node-gyp/10.8.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../binding.cpp:38:39: warning: 'New' is deprecated [-Wdeprecated-declarations]
            Local<Value>::New(String::New(ctx->error_message))
                                      ^
/Users/deepak/.node-gyp/10.8.0/include/node/v8.h:4043:12: note: 'New' has been explicitly marked deprecated here
    static V8_DEPRECATED("Use maybe version",
           ^
/Users/deepak/.node-gyp/10.8.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../binding.cpp:41:24: error: member reference type 'v8::Persistent<v8::Function>' is not a pointer; did you mean to use '.'?
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
        ~~~~~~~~~~~~~~~^~
                       .
../binding.cpp:41:26: error: no member named 'Call' in 'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
        ~~~~~~~~~~~~~~~  ^
../binding.cpp:41:40: error: no member named 'GetCurrent' in 'v8::Context'
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
                              ~~~~~~~~~^
../binding.cpp:50:31: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> OldRender(const Arguments& args) {
                              ^~~~~~~~~
                              v8::internal::Arguments
/Users/deepak/.node-gyp/10.8.0/include/node/v8.h:144:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../binding.cpp:51:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/deepak/.node-gyp/10.8.0/include/node/v8.h:883:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../binding.cpp:55:23: error: expected ';' after expression
    String::AsciiValue astr(args[0]);
                      ^
                      ;
../binding.cpp:55:13: error: no member named 'AsciiValue' in 'v8::String'
    String::AsciiValue astr(args[0]);
    ~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
4 warnings and 20 errors generated.
make: *** [Release/obj.target/binding/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/dashing-js/node_modules/node-sass
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@0.7.0 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/deepak/.npm/_logs/2018-08-07T06_57_14_847Z-debug.log
deepak:~/Downloads$ 
 
```

**Comment by javatechy** [comment]
Node version 10.8.0
